# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_check_user_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from gui import qt_extended_widgets


class Ui_Dialog_user_check(object):
    def setupUi(self, Dialog_user_check):
        Dialog_user_check.setObjectName("Dialog_user_check")
        Dialog_user_check.resize(300, 200)
        Dialog_user_check.setMaximumSize(QtCore.QSize(300, 200))
        self.dialog_user_check_page = QtWidgets.QStackedWidget(Dialog_user_check)
        self.dialog_user_check_page.setGeometry(QtCore.QRect(0, 0, 300, 200))
        self.dialog_user_check_page.setObjectName("dialog_user_check_page")
        self.page_face_id = QtWidgets.QWidget()
        self.page_face_id.setObjectName("page_face_id")
        self.page_face_id_back_frame = QtWidgets.QFrame(self.page_face_id)
        self.page_face_id_back_frame.setGeometry(QtCore.QRect(0, 0, 300, 200))
        self.page_face_id_back_frame.setStyleSheet(".QFrame {\n"
"    \n"
"    background-color: rgb(238, 238, 238);\n"
"}")
        self.page_face_id_back_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page_face_id_back_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_face_id_back_frame.setObjectName("page_face_id_back_frame")
        self.page_face_id_face_animation_frame = QtWidgets.QFrame(self.page_face_id_back_frame)
        self.page_face_id_face_animation_frame.setGeometry(QtCore.QRect(50, 20, 200, 125))
        self.page_face_id_face_animation_frame.setStyleSheet(".QFrame {\n"
"    border: 1px solid #c2ebec;\n"
"    border-radius: 6px;\n"
"    background-color: #c2ebec;\n"
"}")
        self.page_face_id_face_animation_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page_face_id_face_animation_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_face_id_face_animation_frame.setObjectName("page_face_id_face_animation_frame")
        self.page_face_id_face_animation_frame_label = QtWidgets.QLabel(self.page_face_id_face_animation_frame)
        self.page_face_id_face_animation_frame_label.setGeometry(QtCore.QRect(5, 5, 190, 115))
        self.page_face_id_face_animation_frame_label.setStyleSheet(".QLabel {\n"
"    border: 2px dashed #393E46;\n"
"    border-radius: 5px;\n"
"    padding: 40px;\n"
"}")
        self.page_face_id_face_animation_frame_label.setText("")
        self.page_face_id_face_animation_frame_label.setObjectName("page_face_id_face_animation_frame_label")
        self.page_face_id_face_animation_text_label = QtWidgets.QLabel(self.page_face_id_face_animation_frame)
        self.page_face_id_face_animation_text_label.setGeometry(QtCore.QRect(55, 90, 90, 15))
        self.page_face_id_face_animation_text_label.setStyleSheet(".QLabel {\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    color: #222831\n"
"}")
        self.page_face_id_face_animation_text_label.setObjectName("page_face_id_face_animation_text_label")
        self.page_face_id_face_animation_image_label = QtWidgets.QLabel(self.page_face_id_face_animation_frame)
        self.page_face_id_face_animation_image_label.setGeometry(QtCore.QRect(75, 30, 50, 40))
        self.page_face_id_face_animation_image_label.setStyleSheet(".QLabel {\n"
"image: url(:/icons/icons/icons8-sad-96.png);\n"
"}")
        self.page_face_id_face_animation_image_label.setText("")
        self.page_face_id_face_animation_image_label.setObjectName("page_face_id_face_animation_image_label")
        self.page_face_id_cancel_button = QtWidgets.QPushButton(self.page_face_id_back_frame)
        self.page_face_id_cancel_button.setGeometry(QtCore.QRect(40, 160, 105, 30))
        self.page_face_id_cancel_button.setStyleSheet(".QPushButton {\n"
"    background-color:  #393E46;\n"
"    color: #EEEEEE;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #393E46;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    background-color: #00ADB5;\n"
"    border-color:  #00ADB5;\n"
"}")
        self.page_face_id_cancel_button.setObjectName("page_face_id_cancel_button")
        self.page_face_id_using_password_button = QtWidgets.QPushButton(self.page_face_id_back_frame)
        self.page_face_id_using_password_button.setGeometry(QtCore.QRect(155, 160, 105, 30))
        self.page_face_id_using_password_button.setStyleSheet(".QPushButton {\n"
"    background-color:  #393E46;\n"
"    color: #EEEEEE;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #393E46;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    background-color: #00ADB5;\n"
"    border-color:  #00ADB5;\n"
"}")
        self.page_face_id_using_password_button.setObjectName("page_face_id_using_password_button")
        self.dialog_user_check_page.addWidget(self.page_face_id)
        self.page_password_check = QtWidgets.QWidget()
        self.page_password_check.setObjectName("page_password_check")
        self.page_password_check_back_frame = QtWidgets.QFrame(self.page_password_check)
        self.page_password_check_back_frame.setGeometry(QtCore.QRect(0, 0, 300, 200))
        self.page_password_check_back_frame.setStyleSheet(".QFrame {\n"
"    \n"
"    background-color: rgb(238, 238, 238);\n"
"}")
        self.page_password_check_back_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page_password_check_back_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_password_check_back_frame.setObjectName("page_password_check_back_frame")
        self.page_password_check_cancel_button = QtWidgets.QPushButton(self.page_password_check_back_frame)
        self.page_password_check_cancel_button.setGeometry(QtCore.QRect(40, 150, 105, 30))
        self.page_password_check_cancel_button.setStyleSheet(".QPushButton {\n"
"    background-color:  #393E46;\n"
"    color: #EEEEEE;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #393E46;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    background-color: #00ADB5;\n"
"    border-color:  #00ADB5;\n"
"}\n"
"\n"
".QPushButton:pressed {\n"
"    background-color: #222831;\n"
"}")
        self.page_password_check_cancel_button.setObjectName("page_password_check_cancel_button")
        self.page_password_check_see_password_checkbox = QtWidgets.QCheckBox(self.page_password_check_back_frame)
        self.page_password_check_see_password_checkbox.setGeometry(QtCore.QRect(47, 72, 20, 20))
        self.page_password_check_see_password_checkbox.setAutoFillBackground(False)
        self.page_password_check_see_password_checkbox.setStyleSheet("QCheckBox {\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    color: #222831\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    height: 16px;\n"
"    width: 16px;\n"
"    border: 2px solid #393E46;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"image: url(:/icons/icons/icons8-uchiha-eyes-96.png);\n"
"    background-color: #75d2d6;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"image: url(:/icons/icons/icons8-closed-eye-90.png);\n"
"    background-color: #EEEEEE;\n"
"}")
        self.page_password_check_see_password_checkbox.setText("")
        self.page_password_check_see_password_checkbox.setIconSize(QtCore.QSize(12, 12))
        self.page_password_check_see_password_checkbox.setCheckable(True)
        self.page_password_check_see_password_checkbox.setChecked(False)
        self.page_password_check_see_password_checkbox.setObjectName("page_password_check_see_password_checkbox")
        self.page_password_check_enter_password_text_label = QtWidgets.QLabel(self.page_password_check_back_frame)
        self.page_password_check_enter_password_text_label.setGeometry(QtCore.QRect(100, 90, 101, 61))
        self.page_password_check_enter_password_text_label.setStyleSheet(".QLabel {\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    color: #222831\n"
"}")
        self.page_password_check_enter_password_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.page_password_check_enter_password_text_label.setObjectName("page_password_check_enter_password_text_label")
        self.page_password_check_animation_image_label = QtWidgets.QLabel(self.page_password_check_back_frame)
        self.page_password_check_animation_image_label.setGeometry(QtCore.QRect(135, 20, 31, 31))
        self.page_password_check_animation_image_label.setStyleSheet(".QLabel {\n"
"image: url(:/icons/icons/icons8-millenium-eye-96.png);\n"
"}")
        self.page_password_check_animation_image_label.setText("")
        self.page_password_check_animation_image_label.setObjectName("page_password_check_animation_image_label")
        self.page_password_check_submit_button = QtWidgets.QPushButton(self.page_password_check_back_frame)
        self.page_password_check_submit_button.setGeometry(QtCore.QRect(155, 150, 105, 30))
        self.page_password_check_submit_button.setStyleSheet(".QPushButton {\n"
"    background-color:  #393E46;\n"
"    color: #EEEEEE;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #393E46;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    background-color: #00ADB5;\n"
"    border-color:  #00ADB5;\n"
"}\n"
".QPushButton:pressed {\n"
"    background-color: #222831;\n"
"}")
        self.page_password_check_submit_button.setObjectName("page_password_check_submit_button")
        self.page_password_check_enter_password_line_edit = qt_extended_widgets.ChildLineEdit(self.page_password_check_back_frame)
        self.page_password_check_enter_password_line_edit.setGeometry(QtCore.QRect(70, 69, 180, 25))
        self.page_password_check_enter_password_line_edit.setStyleSheet("QLineEdit {\n"
"    background-color:  #393E46;\n"
"     font-size: 12px;\n"
"     font-weight: bold;\n"
"     color: #EEEEEE;\n"
"     padding: 0 10px;\n"
"     border: 2px solid #222831;\n"
"     border-radius: 6px;\n"
"     selection-background-color: darkgray;\n"
"}")
        self.page_password_check_enter_password_line_edit.setText("")
        self.page_password_check_enter_password_line_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.page_password_check_enter_password_line_edit.setReadOnly(False)
        self.page_password_check_enter_password_line_edit.setObjectName("page_password_check_enter_password_line_edit")
        self.dialog_user_check_page.addWidget(self.page_password_check)

        self.retranslateUi(Dialog_user_check)
        self.dialog_user_check_page.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog_user_check)

    def retranslateUi(self, Dialog_user_check):
        _translate = QtCore.QCoreApplication.translate
        Dialog_user_check.setWindowTitle(_translate("Dialog_user_check", "Dialog"))
        self.page_face_id_face_animation_text_label.setText(_translate("Dialog_user_check", "Don\'t recognize :("))
        self.page_face_id_cancel_button.setText(_translate("Dialog_user_check", "Cancel"))
        self.page_face_id_using_password_button.setText(_translate("Dialog_user_check", "Using password"))
        self.page_password_check_cancel_button.setText(_translate("Dialog_user_check", "Cancel"))
        self.page_password_check_enter_password_text_label.setText(_translate("Dialog_user_check", "<html><head/><body><p><span style=\" font-size:8pt;\">........./\\.........<br/>..........|..........<br/>Enter password</span></p></body></html>"))
        self.page_password_check_submit_button.setText(_translate("Dialog_user_check", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_user_check = QtWidgets.QDialog()
    ui = Ui_Dialog_user_check()
    ui.setupUi(Dialog_user_check)
    Dialog_user_check.show()
    sys.exit(app.exec_())
